print("\033[31m", "+++++++++ Create your own adventure +++++++++", "\033[0m")
print()
print("You will be asked to input some information about yourself that will be used to put you in a simulated world!")
print()
myName = input("Your name :")
myCrush = input("Your crush's name :")
myVisit = input("Place you would like to one day visit :")
myEnemy = input("Your worst enemy :")
enemyArea = input("Your enemy's location :")
myTrait = input("Your trait :")

print("Legend say when you stay awake at night thinking about someone, they are probably up too thinking about you. But is that the case for", myName,"?. The story of", myName, "begins when he first laid his eyes on", myCrush, "who, as things would unfold as unfavorable to him was also a sister to his sworn enemy", myEnemy,".")
print()
print(myName, "was a", myTrait, "adventurer, always seeking out new challenges and exciting experiences. But his greatest adversary was",myEnemy,", a notorious bandit who roamed the countryside, terrorizing the innocent and pillaging their goods.")
print()
print("Despite their differences,", myName, "was hopelessly in love with the younger sister to", myEnemy, "a beautiful and fearless warrior named", myCrush, ". He knew that he would need to prove himself worthy of her love, and so he set out on a quest to bring", myEnemy, "to justice and win her heart.")
print()
print("As", myName, "traveled through the rugged terrain, he encountered countless obstacles and dangerous creatures. But he never lost sight of his goal, and he fought bravely, relying on his wit and strength to overcome each challenge.")
print()
print("Finally,", myName, "arrived at", enemyArea, "where", myEnemy, "was hiding, ready to face him in a final showdown. With a fierce battle cry,", myName, "lunged forward, his sword flashing in the sunlight.")
print()
print("And in that moment, everything changed. For as they clashed,", myName, "saw the fear in", myEnemy,"\'s eyes, and he realized that his enemy was not as evil as he had thought. And so, instead of killing him,", myName, "offered", myEnemy, "a hand of friendship, and together they set out to protect the countryside from other dangers.")
print()
print("And as they traveled,", myName, "and", myCrush, "grew closer, until finally they became inseparable, united in their love and their quest for adventure. They later moved to", myVisit, "Where they lived happily ever after")
print()
print("THE END!")